import { ERadioGroup } from './radio'
import { ECheckboxGroup } from './checkbox'
import { EInput } from './input'
import { EInputNumber } from './input-number'
import { ESelect } from './select'
import { ECascader } from './cascader'
import { ESwitch } from './switch'
import { ESlider } from './slider'
import { EDatePicker } from './date-picker'
import { ETimePicker } from './time-picker'
import { ETimeSelect } from './time-select'
import { EUpload } from './upload'
import { EForm } from './form'
import { EFormItem } from './form-item'
import { EFormulate } from './formulate'
import { ETable } from './table'
import { ETableColumn } from './table-column'
import { EPagination } from './pagination'
import { EConfigProvider } from './config-provider'

export class RadioGroup extends ERadioGroup {}
export class CheckboxGroup extends ECheckboxGroup {}
export class Input extends EInput {}
export class InputNumber extends EInputNumber {}
export class Select extends ESelect {}
export class Cascader extends ECascader {}
export class Switch extends ESwitch {}
export class Slider extends ESlider {}
export class DatePicker extends EDatePicker {}
export class TimePicker extends ETimePicker {}
export class TimeSelect extends ETimeSelect {}
export class Upload extends EUpload {}
export class Form extends EForm {}
export class FormItem extends EFormItem {}
export class Formulate extends EFormulate {}
export class Table extends ETable {}
export class TableColumn extends ETableColumn {}
export class Pagination extends EPagination {}
export class ConfigProvider extends EConfigProvider {}

export { useRadioGroup } from './radio'
export { useCheckboxGroup } from './checkbox'
export { useInput } from './input'
export { useInputNumber } from './input-number'
export { useSelect } from './select'
export { useCascader } from './cascader'
export { useSwitch } from './switch'
export { useSlider } from './slider'
export { useDatePicker } from './date-picker'
export { useUpload } from './upload'
export { useForm } from './form'
export { useFormItem } from './form-item'
export { useFormulate } from './formulate'
export { useTable } from './table'
export { useTableColumn } from './table-column'
export { usePagination } from './pagination'
export { useConfigProvider } from './config-provider'